package domain;

public enum Enfermedades {
	NINGUNA,ENFERMEDADES_CARDIOVASCULARES, ENFERMEDADES_RESPIRATORIAS_CRÓNICAS, 
	ENFERMEDADES_INFECCIOSAS, DIABETES, CÁNCER, ENFERMEDADES_MENTALES,
	ENFERMEDADES_MUSCULOESQUELÉTICAS, ENFERMEDADES_DEL_SISTEMA_DIGESTIVO, 
	ENFERMEDADES_ENDOCRINAS, ENFERMEDADES_RENALES, ENFERMEDADES_NEUROLÓGICAS, 
	ENFERMEDADES_DE_TRANSMISIÓN_SEXUAL, OBESIDAD
}
