package domain;

public enum TipoEnfermedades {
	NINGUNA,CARDIOVASCULARES, RESPIRATORIAS, INFECCIOSAS, DIABETES, CANCER, MENTALES,
	MUSCULOESQUELETICAS, DIGESTIVAS, ENDOCRINAS, RENALES, NEUROLOGICAS, ETS, OBESIDAD
}
