package domain;

public enum TipoAlergias {
	NINGUNA, GLUTEN, CRUSTACEOS, MOLUSCOS, PESCADO, HUEVOS, ALTRAMUCES, MOSTAZA, CACAHUETES, 
	FRUTOS_DE_CASCARA, SOJA, SESAMO, APIO, LÁCTEOS , SULFITOS}
